config/routes.rb
Rails.application.routes.draw do
  get '/contact', to: 'static#contact'
  get '/team', to: 'static#team'
  root 'home#index'
  get '/welcome/:name', to: 'welcome#user'
  resources :gossip
  resources :user, except: [:destroy]
  resources :city, except: [:destroy] 
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    #validates :title, length: { in: 3..14 }, presence: true
    #validates :content, presence: true
    belongs_to :user
    has_many :join_table_gossip_tags
    has_many :tags, through: :join_table_gossip_tags
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :join_table_gossip_tags
    has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    belongs_to :city
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @id = params[:id]
    @cities = City.all
    @gossips = Gossip.where(user:User.find_by(city:params[:id]))
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @id = params[:id]
    @gossips = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)
    if @gossip.save
    redirect_to root_path
  else
    flash.now[:danger] = 'Invalid email/password combination'
    puts "$" * 60
    render 'new'
    puts "$" * 60
  end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(gossip_params)
    redirect_to gossip_path
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

private 

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
        else
            @gossips = Gossip.all
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    
    def create
        # cherche s'il existe un utilisateur en base avec l’e-mail
        user = User.find_by(email: params[:email])
        puts "$" * 60
        puts params 
        puts "$" * 60     
        # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          # redirige où tu veux, avec un flash ou pas
            puts "#{session[:user_id]} " * 60
            redirect_to root_path
        else
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
        end
      end

      def destroy
        session.delete(:user_id)
        redirect_to root_path
      end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
  
  def show
    @users = User.all
    @id = params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation], age: params[:age], first_name: params[:first_name], last_name: params[:last_name], description: params[:description], city: City.last) 
    if @user.save
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      puts "$" * 60
      render 'new'
      puts "$" * 60
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def user
    @user_name = params[:name]
    @gossips = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../assets/stylesheets/application.css">
    <title>The Gossip Project</title>
</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">The Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "Home", root_path, :class => "nav-item nav-link  active" %> 
            </li>
            <li class="nav-item">
              <%= link_to "Team", team_path, :class => "nav-item nav-link" %> 
            </li>
            <li class="nav-item">
              <%= link_to "Contact", contact_path, :class => "nav-item nav-link" %> 
            </li>
          </ul>
          <span class="navbar-text">
            <%= link_to "Log Out", session_path(session.id), method: :delete, class: "btn btn-outline-danger", id: "logout" %>
          </span>
        </div>
      </nav>

      <div class="container">
        <h1 class="text-center mt-4">Welcome <%= User.find_by(id: session[:user_id]).first_name %></h1>
        <h4 class="text-muted text-center mb-5">Let's bitchin' !</h3>
        <%= link_to "Create a new Gossip", new_gossip_path, class: "btn btn-success" %>
        <h4 class="text-muted mt-4 mb-4">Gossip List :</h4>
        <div class="row row-cols-3">
          <% @gossips.each do |g| %>
          <div class="col mb-5">
          <div class="card" style="width: 18rem; height: 8rem;">
            <div class="card-body">
              <h5 class="card-title text-center"><%= link_to g.title, gossip_path(@id = g.id), :class => "text-center" %></h5>
              <h6 class="card-subtitle mb-4 text-muted text-center"><%= g.user.first_name + " " + g.user.last_name %></h6>
            </div>
          </div>
        </div>
          <% end %>
        </div>
      </div>


</body>
</html>